"""add_description_to_fee_template

Revision ID: 298c06171178
Revises: 39f7d9637be2
Create Date: 2026-06-29 18:29:44.655033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '298c06171178'
down_revision: Union[str, Sequence[str], None] = '39f7d9637be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_templates', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fee_templates', 'description')
    # ### end Alembic commands ###
