"""add webhook logs and update transaction status

Revision ID: 3f0a1c9bcdea
Revises: b1084524b36d
Create Date: 2026-07-02 17:37:08.339566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f0a1c9bcdea'
down_revision: Union[str, Sequence[str], None] = 'b1084524b36d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_logs',
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.add_column('transactions', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('checkout_url', sa.String(length=512), nullable=True))
    op.add_column('transactions', sa.Column('customer_phone', sa.String(length=20), nullable=True))
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'updated_at')
    op.drop_column('transactions', 'customer_phone')
    op.drop_column('transactions', 'checkout_url')
    op.drop_column('transactions', 'payment_method')
    op.drop_table('webhook_logs')
    # ### end Alembic commands ###
