"""add billing configurations and compulsory flag

Revision ID: 9ffe03c939e8
Revises: b0e454b8c525
Create Date: 2026-05-22 18:16:05.202296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ffe03c939e8'
down_revision: Union[str, Sequence[str], None] = 'b0e454b8c525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_line_items', sa.Column('is_compulsory', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fee_line_items', 'is_compulsory')
    # ### end Alembic commands ###
