"""clear and update bank settlements schema - removed nomba subaccount id

Revision ID: a34e73fb64cc
Revises: 4fe1ece2ea44
Create Date: 2026-07-04 03:53:29.397678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34e73fb64cc'
down_revision: Union[str, Sequence[str], None] = '4fe1ece2ea44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_settlements', 'nomba_subaccount_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_settlements', sa.Column('nomba_subaccount_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
