"""add_parent_email_and_transaction_relations

Revision ID: b06709e49617
Revises: 9ffe03c939e8
Create Date: 2026-05-24 22:38:33.663504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06709e49617'
down_revision: Union[str, Sequence[str], None] = '9ffe03c939e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('parent_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'parent_email')
    # ### end Alembic commands ###
