"""add_onboarding_and_bank_settlement

Revision ID: b1084524b36d
Revises: 298c06171178
Create Date: 2026-06-30 09:50:01.380480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1084524b36d'
down_revision: Union[str, Sequence[str], None] = '298c06171178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('nomba_subaccount_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    # Added server_default here to handle existing rows safely!
    op.add_column('organizations', sa.Column('has_setup_bank', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('organizations', sa.Column('is_onboarding_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'is_onboarding_completed')
    op.drop_column('organizations', 'has_setup_bank')
    op.drop_table('bank_settlements')
    # ### end Alembic commands ###
